version: :latest

services:
  planka:
    image: ghcr.io/plankanban/planka:latest
    restart: on-failure
    volumes:
      - user-avatars:/app/public/user-avatars
      - project-background-images:/app/public/project-background-images
      - attachments:/app/private/attachments
    ports:
      - 3000:1337
    environment:
      - BASE_URL=http://10.0.0.126:3000
      - DATABASE_URL=postgresql://dummy_user:dummypassword@postgres/planka # Replace with your PostgreSQL username and password
      - SECRET_KEY=super_secret_key_123456 # Replace with a secure secret key for your application

      - TRUST_PROXY=1
      # - TOKEN_EXPIRES_IN=365 # In days

      # Uncomment for SSL configuration if needed
      # - PGSSLMODE=require
      # - KNEX_REJECT_UNAUTHORIZED_SSL_CERTIFICATE=false

      - DEFAULT_ADMIN_EMAIL=billygoat@p1ng.co.co # Important to keep this for the admin
      - DEFAULT_ADMIN_PASSWORD=aKANP!NG0@0!0 # Replace with a secure password
      - DEFAULT_ADMIN_NAME=Marc van Heerden
      - DEFAULT_ADMIN_USERNAME=billygoat

      # Uncomment to show detailed errors (use caution).
      # - SHOW_DETAILED_AUTH_ERRORS=false 

      # Uncomment if you want to allow all users to create projects
      # - ALLOW_ALL_TO_CREATE_PROJECTS=true

      # OIDC configurations (uncomment and fill in when needed)
      # - OIDC_ISSUER=
      # - OIDC_CLIENT_ID=
      # - OIDC_CLIENT_SECRET=
      
      # Email Notifications (for SMTP)
      # - SMTP_HOST=
      # - SMTP_PORT=587
      # - SMTP_NAME=
      # - SMTP_SECURE=true
      # - SMTP_USER=
      # - SMTP_PASSWORD=
      # - SMTP_FROM="Demo User" <demo@example.com>
      # - SMTP_TLS_REJECT_UNAUTHORIZED=false
      
      # For webhooks and integrations, uncomment and configure as needed
      # - WEBHOOKS=[{ "url": "http://localhost:3001", ... }]
      # - SLACK_BOT_TOKEN=
      # - SLACK_CHANNEL_ID=
      # - GOOGLE_CHAT_WEBHOOK_URL=
      
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:14-alpine
    restart: on-failure
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=planka
      - POSTGRES_USER=dummy_user # Replace with your desired PostgreSQL username
      - POSTGRES_PASSWORD=dummypassword # Replace with a secure password for your PostgreSQL user
      - POSTGRES_HOST_AUTH_METHOD=md5 # Change to 'md5' for better security
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dummy_user -d planka"] # Update to use your PostgreSQL username
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  user-avatars:
  project-background-images:
  attachments:
  db-data:
